### ISSUE TITLE
TravisCI Badge Points to Wrong Branch

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/findings-data-import-lambda#4]
# 🐛 Bug Report

The badge for TravisCI is pointing to the master branch which no longer exists (we use develop as our main branch).

## To Reproduce

Visit the repository and look at the URL for the TravisCI badge in README.md

## Expected behavior

Badge should reference the develop branch.

**Comment by mzack5020** [comment]
See #6. Change was made. Thanks for catching that.

**Comment by mzack5020** [comment]
#6 Pull request was merged and approved. Thanks for catching that.
