### ISSUE TITLE
Condense Build Instructions

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/findings-data-import-lambda#5]
I would like to see the build instructions condensed down to one multi-line code block with appropriate formatting. The [cyhy-feeds](https://github.com/cisagov/cyhy-feeds) repository has some examples.

**Comment by mzack5020** [comment]
Are you talking about this section of the README?

![image](https://user-images.githubusercontent.com/12749393/64431159-de490300-d087-11e9-8e46-23d9b09508f9.png)

**Comment by mzack5020** [comment]
^ @mcdonnnj

**Comment by mcdonnnj** [comment]
Yes, that is the section I meant.

**Comment by mzack5020** [comment]
Made the change. See PR #7

**Comment by mzack5020** [comment]
#7 PR Merged. Thanks
